export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  WASLOGIN: 'WASLOGIN',
  OPEN_MESSAGE: 'OPEN_MESSAGE',
  CLOSE_MESSAGE: 'CLOSE_MESSAGE',
  SET_PRODUCT: 'SET_PRODUCT',
  RESET_PRODUCT: 'RESET_PRODUCT',
  SET_GROUP: 'SET_GROUP',
};
