export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  WASLOGIN: 'WASLOGIN',
  OPEN_MESSAGE: 'OPEN_MESSAGE',
  CLOSE_MESSAGE: 'CLOSE_MESSAGE',
};
